# Patronage links for GitHub's "Sponsor" button.
# Keep values in sync with README support section.

github: [jjhickman]
patreon: garbanzobot
# ko_fi: your_kofi_handle
custom:
  - https://github.com/sponsors/jjhickman
  - https://www.patreon.com/c/garbanzobot
