import { bold } from '../utils/formatting.js';

/**
 * Help command — shows users what Garbanzo can do.
 */

export function getHelpMessage(): string {
  return [
    `${bold('Hey, I\'m Garbanzo Bean!')} 🫘`,
    'Your Boston community bot. Here\'s what I can do:',
    '',
    `${bold('Weather')}`,
    '  !weather — current conditions in Boston',
    '  !weather [city] — weather elsewhere',
    '  !forecast — 5-day forecast',
    '',
    `${bold('MBTA Transit')}`,
    '  !transit — current service alerts',
    '  !transit [station] — live arrivals',
    '  !mbta red line — line status',
    '',
    `${bold('News')}`,
    '  !news — top US headlines',
    '  !news [topic] — search for articles',
    '',
    `${bold('Events')}`,
    '  !events [idea] — plan an outing',
    '',
    `${bold('D&D 5e')}`,
    '  !roll d20 — roll dice',
    '  !roll 2d6+3 — multiple dice + modifier',
    '  !dnd spell fireball — spell lookup',
    '  !dnd monster goblin — monster stats',
    '  !dnd class wizard — class info',
    '  !dnd item longsword — equipment lookup',
    '',
    `${bold('Venues')}`,
    '  !venue bars in somerville — search near Boston',
    '  !venue escape rooms — find places',
    '  !venue details [name] — phone, hours, website',
    '',
    `${bold('Book Club')}`,
    '  !book [title] — search by title',
    '  !book author [name] — books by author',
    '  !book isbn [number] — ISBN lookup',
    '',
    `${bold('Polls')}`,
    '  !poll Question? / Option 1 / Option 2 / Option 3',
    '  !poll multi Pick two / A / B / C — multi-select',
    '',
    `${bold('Fun')}`,
    '  !trivia — random trivia question',
    '  !trivia [category] — by category',
    '  !fact — random fun fact',
    '  !today — this day in history',
    '  !icebreaker — conversation starter',
    '',
    `${bold('Anything Else')}`,
    '  Just ask! I can answer questions, give Boston',
    '  recs, or chat about whatever.',
    '',
    '_You can also use natural language — "what\'s the weather?" works too._',
    '_@mention me in any group to get started._',
  ].join('\n');
}
