import { bold } from '../utils/formatting.js';
import { getPersonaEmoji, getPersonaName } from '../ai/persona.js';

/**
 * Help command — shows users what Garbanzo can do.
 *
 * Separate help for regular members and owner-only commands.
 */

/** Build the standard member-facing help message. */
export function getHelpMessage(): string {
  return [
    `${bold(`Hey, I'm ${getPersonaName()}!`)}${getPersonaEmoji() ? ` ${getPersonaEmoji()}` : ''}`,
    'Your Boston community bot. Here\'s what I can do:',
    '',
    `${bold('Weather')}`,
    '  !weather — current conditions in Boston',
    '  !weather [city] — weather elsewhere',
    '  !forecast — 5-day forecast',
    '',
    `${bold('MBTA Transit')}`,
    '  !transit — current service alerts',
    '  !transit [station] — live arrivals',
    '  !mbta red line — line status',
    '',
    `${bold('News')}`,
    '  !news — top US headlines',
    '  !news [topic] — search for articles',
    '',
    `${bold('Events')}`,
    '  !events [idea] — plan an outing',
    '',
    `${bold('D&D 5e')}`,
    '  !roll d20 — roll dice',
    '  !roll 2d6+3 — multiple dice + modifier',
    '  !dnd spell fireball — spell lookup',
    '  !dnd monster goblin — monster stats',
    '  !dnd class wizard — class info',
    '  !dnd item longsword — equipment lookup',
    '',
    `${bold('Venues')}`,
    '  !venue bars in somerville — search near Boston',
    '  !venue escape rooms — find places',
    '  !venue details [name] — phone, hours, website',
    '',
    `${bold('Book Club')}`,
    '  !book [title] — search by title',
    '  !book author [name] — books by author',
    '  !book isbn [number] — ISBN lookup',
    '',
    `${bold('Polls')}`,
    '  !poll Question? / Option 1 / Option 2 / Option 3',
    '  !poll multi Pick two / A / B / C — multi-select',
    '',
    `${bold('Character Sheets')}`,
    '  !character — random Level 1 character + PDF',
    '  !character elf wizard — specify race/class',
    '  !char dwarf — random class, specific race',
    '',
    `${bold('Fun')}`,
    '  !trivia — random trivia question',
    '  !trivia [category] — by category',
    '  !fact — random fun fact',
    '  !today — this day in history',
    '  !icebreaker — conversation starter',
    '',
    `${bold('Your Profile')}`,
    '  !profile — view your profile',
    '  !profile interests hiking, cooking — set interests',
    '  !profile name Alex — set display name',
    '  !profile delete — remove your data',
    '',
    `${bold('Conversation')}`,
    '  !summary — summarize recent chat (last 50 msgs)',
    '  !summary 100 — summarize last 100 messages',
    '  !catchup / !missed — same as !summary',
    '  !recommend / !recs — event ideas based on your interests',
    '',
    `${bold('Voice & Media')}`,
    '  !voice — speak the replied-to message aloud',
    '  !voice british — use a specific voice',
    '  !voice list — show all available voices',
    '  Send an image/video/sticker and @mention me — I\'ll describe it',
    '  Send a voice note — I\'ll transcribe and respond',
    '  Share a YouTube link — I\'ll transcribe and summarize',
    '',
    `${bold('Feedback')}`,
    '  !suggest <idea> — submit a feature suggestion',
    '  !bug <description> — report a bug',
    '  !upvote <id> — upvote an existing suggestion/report',
    '',
    `${bold('Anything Else')}`,
    '  Just ask! I can answer questions, give Boston',
    '  recs, or chat about whatever.',
    '',
    '_You can also use natural language — "what\'s the weather?" works too._',
    '_Send me images, voice notes, or links — I understand multimedia._',
    '_@mention me in any group to get started._',
  ].join('\n');
}

/**
 * Owner-only help — shown in DM when owner sends !help admin or !admin.
 */
export function getOwnerHelpMessage(): string {
  return [
    `${bold('Owner Commands')} 🔧`,
    '',
    `${bold('Memory')}`,
    '  !memory — list all stored community facts; auto-extracted facts are tagged',
    '  !memory add <category> <fact> — store an owner fact',
    '  !memory delete <id> — remove a fact',
    '  !memory search <keyword> — search facts',
    '',
    `${bold('Feedback Review')}`,
    '  !feedback — view all pending suggestions/bugs',
    '  !feedback all — summary of recent feedback',
    '  !feedback accept <id> — mark feedback accepted',
    '  !feedback reject <id> — reject feedback item',
    '  !feedback done <id> — mark feedback item completed',
    '  !feedback issue <id> — create GitHub issue for accepted item',
    '',
    `${bold('Moderation')}`,
    '  !strikes — view strike counts',
    '  !catchup intros — recent introductions summary',
    '',
    `${bold('Reports')}`,
    '  !digest — preview today\'s digest so far',
    '  !recap — weekly community recap (last 7 days)',
    '',
    `${bold('Event Reminders')}`,
    '  !events — list upcoming pending event reminders',
    '  !events cancel <id> — cancel a pending event reminder',
    '',
    `${bold('Native Events')} (in group chats; band members can use these too)`,
    '  !event <when> | <name> [| location] — create a platform event',
    '  !event list — upcoming events in the chat',
    '  !event show <id> — event details',
    '  !event move <id> <when> — reschedule an event',
    '  !event rename <id> <name> — rename an event',
    '  !event cancel <id> — cancel an event',
    '',
    `${bold('WhatsApp Safety')}`,
    '  !whatsapp status — view risk, retained jobs, and send counts',
    '  !whatsapp pause / resume — control new outbound sends',
    '  !whatsapp held — list retained outbound jobs',
    '  !whatsapp release <id> — explicitly send a retained job',
    '  !whatsapp discard <id> — discard a retained job',
    '',
    `${bold('Releases')}`,
    '  !release rules — show member-facing release update rules',
    '  !release preview <notes> — lint + format only (no send)',
    '  !release send <notes> — broadcast to all enabled groups',
    '  !release send <group> <notes> — broadcast to one group',
    '  !release send changelog [lines] — send latest changelog snippet',
    '  !release internal <notes> — keep update operator-only',
    '',
    `${bold('Support')}`,
    '  !support — preview support links message',
    '  !support broadcast — send support message to all enabled groups',
    '',
    '_These commands only work in DM with the bot._',
  ].join('\n');
}
