import { afterEach, describe, expect, it, vi } from 'vitest';

const originalEnv = { ...process.env };
const exitSpy = vi.spyOn(process, 'exit').mockImplementation((() => {
  throw new Error('process.exit called');
}) as never);
vi.spyOn(console, 'error').mockImplementation(() => undefined);

const canonicalEnv = {
  MESSAGING_PLATFORM: 'whatsapp',
  OWNER_JID: 'test_owner@s.whatsapp.net',
  LOG_LEVEL: 'debug',
  ANTHROPIC_API_KEY: 'test_anthropic_key',
  OPENROUTER_API_KEY: 'test_openrouter_key',
  OPENAI_API_KEY: 'test_openai_key',
  GEMINI_API_KEY: 'test_gemini_key',
  AI_PROVIDER_ORDER: 'openrouter, anthropic, openrouter, openai',
  ANTHROPIC_MODEL: 'claude-test',
  ANTHROPIC_PRICING_INPUT_PER_M: '2.5',
  ANTHROPIC_PRICING_OUTPUT_PER_M: '7.5',
  ANTHROPIC_PROMPT_CACHING: 'false',
  OPENROUTER_MODEL: 'openrouter/test-model',
  OPENAI_MODEL: 'gpt-test',
  OPENAI_PRICING_INPUT_PER_M: '1.25',
  OPENAI_PRICING_OUTPUT_PER_M: '3.75',
  OPENAI_AUTH_MODE: 'apikey',
  GEMINI_MODEL: 'gemini-test',
  GEMINI_PRICING_INPUT_PER_M: '0.5',
  GEMINI_PRICING_OUTPUT_PER_M: '1.5',
  CLOUD_REQUEST_TIMEOUT_MS: '45000',
  RETRY_ATTEMPT_TIMEOUT_MS: '9000',
  AI_TOOL_CALLING: 'yes',
  AI_TOOL_MAX_ITERATIONS: '4',
  BEDROCK_REGION: 'us-west-2',
  BEDROCK_MODEL_ID: 'bedrock-test',
  BEDROCK_MAX_TOKENS: '2048',
  BEDROCK_PRICING_INPUT_PER_M: '0.75',
  BEDROCK_PRICING_OUTPUT_PER_M: '2.25',
  OLLAMA_BASE_URL: 'http://localhost:11434',
  OLLAMA_MODEL: 'llama-test',
  BOT_PHONE_NUMBER: '15550000000',
  WHATSAPP_LOGIN_MODE: 'both',
  WHATSAPP_LOGIN_TOKEN: 'login-token',
  WHATSAPP_SAFETY_ENABLED: 'false',
  WHATSAPP_SAFETY_MAX_PER_MINUTE: '7',
  WHATSAPP_SAFETY_MAX_PER_HOUR: '200',
  WHATSAPP_SAFETY_MAX_PER_DAY: '3000',
  WHATSAPP_SAFETY_MIN_DELAY_MS: '1000',
  WHATSAPP_SAFETY_MAX_DELAY_MS: '9000',
  WHATSAPP_SAFETY_WARMUP_DAYS: '12',
  WHATSAPP_SAFETY_DAY1_LIMIT: '1000',
  WHATSAPP_SAFETY_AUTO_PAUSE_AT: 'high',
  EVENT_REMINDERS_ENABLED: 'off',
  EVENT_REMINDER_LEAD_MINUTES: '90',
  REHEARSAL_REMINDER_LEAD_MINUTES: '60',
  GOOGLE_API_KEY: 'test_google_key',
  MBTA_API_KEY: 'test_mbta_key',
  NEWSAPI_KEY: 'test_news_key',
  FIRECRAWL_API_KEY: 'test_firecrawl_key',
  BRAVE_SEARCH_API_KEY: 'test_brave_key',
  GOOGLE_SEARCH_ENGINE_ID: 'test_search_engine',
  SEARXNG_BASE_URL: 'http://searxng.local',
  WEB_SEARCH_PROVIDER: 'brave',
  GITHUB_SPONSORS_URL: 'https://github.com/sponsors/example',
  PATREON_URL: 'https://patreon.com/example',
  KOFI_URL: 'https://ko-fi.com/example',
  SUPPORT_CUSTOM_URL: 'https://example.com/support',
  SUPPORT_MESSAGE: '  support us  ',
  GITHUB_ISSUES_TOKEN: 'test_github_token',
  GITHUB_ISSUES_REPO: 'example/repo',
  HEALTH_PORT: '3999',
  HEALTH_BIND_HOST: '0.0.0.0',
  METRICS_ENABLED: 'on',
  MONITORING_TOKEN: '  monitoring-token  ',
  ADMIN_PAGE_ENABLED: 'no',
  WEEKLY_RECAP_ENABLED: '0',
  SLACK_BOT_TOKEN: 'test_slack_bot',
  SLACK_SIGNING_SECRET: 'test_slack_secret',
  SLACK_BOT_USER_ID: 'U123',
  SLACK_CLIENT_ID: 'slack-client',
  SLACK_CLIENT_SECRET: 'slack-secret',
  SLACK_REFRESH_TOKEN: 'slack-refresh',
  SLACK_TOKEN_STATE_FILE: 'data/test-slack-token-state.json',
  SLACK_TOKEN_ROTATE_MIN_BUFFER: '15',
  SLACK_EVENTS_PORT: '4100',
  SLACK_EVENTS_BIND_HOST: '0.0.0.0',
  SLACK_DEMO: 'true',
  SLACK_DEMO_PORT: '4101',
  SLACK_DEMO_BIND_HOST: '0.0.0.0',
  DEMO_TURNSTILE_ENABLED: 'true',
  DEMO_TURNSTILE_SITE_KEY: 'turnstile-site',
  DEMO_TURNSTILE_SECRET_KEY: 'turnstile-secret',
  DISCORD_BOT_TOKEN: 'test_discord_bot',
  DISCORD_PUBLIC_KEY: 'test_discord_public',
  DISCORD_OWNER_ID: 'discord-owner',
  DISCORD_GATEWAY_ENABLED: 'false',
  DISCORD_DIGEST_CHANNEL_ID: 'digest-channel',
  DISCORD_RECAP_CHANNEL_ID: 'recap-channel',
  DISCORD_PRACTICE_CHANNEL_ID: 'practice-channel',
  DISCORD_CHANNELS_CONFIG_PATH: 'config/test-discord-channels.json',
  DISCORD_INTERACTIONS_PORT: '4200',
  DISCORD_INTERACTIONS_BIND_HOST: '0.0.0.0',
  DISCORD_DEMO: 'true',
  DISCORD_DEMO_PORT: '4201',
  DISCORD_DEMO_BIND_HOST: '0.0.0.0',
  DB_DIALECT: 'postgres',
  DATABASE_URL: 'postgres://garbanzo_user:garbanzo_password@postgres.local:6543/garbanzo_test',
  POSTGRES_HOST: 'postgres.local',
  POSTGRES_PORT: '6543',
  POSTGRES_DB: 'garbanzo_test',
  POSTGRES_USER: 'garbanzo_user',
  POSTGRES_PASSWORD: 'garbanzo_password',
  POSTGRES_SSL: 'true',
  POSTGRES_SSL_REJECT_UNAUTHORIZED: 'true',
  CONTEXT_SESSION_MEMORY_ENABLED: 'false',
  CONTEXT_SESSION_GAP_MINUTES: '45',
  CONTEXT_SESSION_MIN_MESSAGES: '5',
  CONTEXT_SESSION_MAX_RETRIEVED: '4',
  CONTEXT_SESSION_SUMMARY_VERSION: '2',
  MEMORY_AUTO_EXTRACT: 'true',
  MEMORY_AUTO_EXTRACT_MIN_MESSAGES: '30',
  MEMORY_AUTO_EXTRACT_INTERVAL_MINUTES: '720',
  MEMORY_AUTO_MAX_FACTS: '300',
  BAND_FEATURES_ENABLED: 'true',
  INSTANCE_ID: 'discord-band',
  BRIDGE_ENABLED: 'true',
  BRIDGE_TRANSPORT: 'amqp',
  BRIDGE_BROKER_URL: '  amqp://bridge-broker  ',
  BRIDGE_SUMMARY_INTERVAL_MINUTES: '9',
  BRIDGE_MAX_TEXT: '800',
  SHARED_MEMORY_ENABLED: 'true',
  QDRANT_SHARED_COLLECTION: 'test_shared_memory',
  VECTOR_STORE: 'qdrant',
  QDRANT_URL: 'http://qdrant.local:6333',
  QDRANT_API_KEY: '  qdrant-key  ',
  QDRANT_COLLECTION: 'test_memory',
  VECTOR_EMBEDDING_PROVIDER: 'openai',
  VECTOR_EMBEDDING_MODEL: 'embedding-test',
  VECTOR_EMBEDDING_DIMENSIONS: '768',
  VECTOR_EMBEDDING_TIMEOUT_MS: '15000',
  VECTOR_EMBEDDING_MAX_CHARS: '5000',
};

async function importConfigWithCanonicalEnv() {
  vi.resetModules();
  vi.doMock('dotenv', () => ({
    config: vi.fn(),
  }));
  process.env = { ...canonicalEnv };
  return import('../src/utils/config.js');
}

describe('config module parity', () => {
  afterEach(() => {
    vi.resetModules();
    vi.doUnmock('dotenv');
    process.env = { ...originalEnv };
    exitSpy.mockClear();
  });

  it('preserves the parsed config key set and representative values', async () => {
    const { config, instanceId } = await importConfigWithCanonicalEnv();

    expect(Object.keys(config).sort()).toMatchInlineSnapshot(`
      [
        "ADMIN_PAGE_ENABLED",
        "AI_PROVIDER_ORDER",
        "AI_TOOL_CALLING",
        "AI_TOOL_MAX_ITERATIONS",
        "ANTHROPIC_API_KEY",
        "ANTHROPIC_MODEL",
        "ANTHROPIC_PRICING_INPUT_PER_M",
        "ANTHROPIC_PRICING_OUTPUT_PER_M",
        "ANTHROPIC_PROMPT_CACHING",
        "BAND_FEATURES_ENABLED",
        "BEDROCK_MAX_TOKENS",
        "BEDROCK_MODEL_ID",
        "BEDROCK_PRICING_INPUT_PER_M",
        "BEDROCK_PRICING_OUTPUT_PER_M",
        "BEDROCK_REGION",
        "BOT_PHONE_NUMBER",
        "BRAVE_SEARCH_API_KEY",
        "BRIDGE_BROKER_URL",
        "BRIDGE_ENABLED",
        "BRIDGE_MAX_TEXT",
        "BRIDGE_SUMMARY_INTERVAL_MINUTES",
        "BRIDGE_TRANSPORT",
        "CLOUD_MAX_TOKENS",
        "CLOUD_REQUEST_TIMEOUT_MS",
        "CONTEXT_SESSION_GAP_MINUTES",
        "CONTEXT_SESSION_MAX_RETRIEVED",
        "CONTEXT_SESSION_MEMORY_ENABLED",
        "CONTEXT_SESSION_MIN_MESSAGES",
        "CONTEXT_SESSION_SUMMARY_VERSION",
        "DATABASE_URL",
        "DB_DIALECT",
        "DEMO_TURNSTILE_ENABLED",
        "DEMO_TURNSTILE_SECRET_KEY",
        "DEMO_TURNSTILE_SITE_KEY",
        "DISCORD_BOT_TOKEN",
        "DISCORD_CHANNELS_CONFIG_PATH",
        "DISCORD_DEMO",
        "DISCORD_DEMO_BIND_HOST",
        "DISCORD_DEMO_PORT",
        "DISCORD_DIGEST_CHANNEL_ID",
        "DISCORD_GATEWAY_ENABLED",
        "DISCORD_INTERACTIONS_BIND_HOST",
        "DISCORD_INTERACTIONS_PORT",
        "DISCORD_OWNER_ID",
        "DISCORD_PRACTICE_CHANNEL_ID",
        "DISCORD_PUBLIC_KEY",
        "DISCORD_RECAP_CHANNEL_ID",
        "EVENT_REMINDERS_ENABLED",
        "EVENT_REMINDER_LEAD_MINUTES",
        "FIRECRAWL_API_KEY",
        "GEMINI_API_KEY",
        "GEMINI_MODEL",
        "GEMINI_PRICING_INPUT_PER_M",
        "GEMINI_PRICING_OUTPUT_PER_M",
        "GITHUB_ISSUES_REPO",
        "GITHUB_ISSUES_TOKEN",
        "GITHUB_SPONSORS_URL",
        "GOOGLE_API_KEY",
        "GOOGLE_SEARCH_ENGINE_ID",
        "HEALTH_BIND_HOST",
        "HEALTH_PORT",
        "INSTANCE_ID",
        "KOFI_URL",
        "LOG_LEVEL",
        "MBTA_API_KEY",
        "MEMORY_AUTO_EXTRACT",
        "MEMORY_AUTO_EXTRACT_INTERVAL_MINUTES",
        "MEMORY_AUTO_EXTRACT_MIN_MESSAGES",
        "MEMORY_AUTO_MAX_FACTS",
        "MESSAGING_PLATFORM",
        "METRICS_ENABLED",
        "MONITORING_TOKEN",
        "NEWSAPI_KEY",
        "OLLAMA_BASE_URL",
        "OLLAMA_MODEL",
        "OPENAI_API_KEY",
        "OPENAI_AUTH_MODE",
        "OPENAI_MODEL",
        "OPENAI_PRICING_INPUT_PER_M",
        "OPENAI_PRICING_OUTPUT_PER_M",
        "OPENAI_REASONING_EFFORT",
        "OPENROUTER_API_KEY",
        "OPENROUTER_MODEL",
        "OWNER_JID",
        "PATREON_URL",
        "POSTGRES_DB",
        "POSTGRES_HOST",
        "POSTGRES_PASSWORD",
        "POSTGRES_PORT",
        "POSTGRES_SSL",
        "POSTGRES_SSL_REJECT_UNAUTHORIZED",
        "POSTGRES_USER",
        "QDRANT_API_KEY",
        "QDRANT_COLLECTION",
        "QDRANT_SHARED_COLLECTION",
        "QDRANT_URL",
        "REHEARSAL_REMINDER_LEAD_MINUTES",
        "RETRY_ATTEMPT_TIMEOUT_MS",
        "SEARXNG_BASE_URL",
        "SHARED_MEMORY_ENABLED",
        "SLACK_BOT_TOKEN",
        "SLACK_BOT_USER_ID",
        "SLACK_CLIENT_ID",
        "SLACK_CLIENT_SECRET",
        "SLACK_DEMO",
        "SLACK_DEMO_BIND_HOST",
        "SLACK_DEMO_PORT",
        "SLACK_EVENTS_BIND_HOST",
        "SLACK_EVENTS_PORT",
        "SLACK_REFRESH_TOKEN",
        "SLACK_SIGNING_SECRET",
        "SLACK_TOKEN_ROTATE_MIN_BUFFER",
        "SLACK_TOKEN_STATE_FILE",
        "SUPPORT_CUSTOM_URL",
        "SUPPORT_MESSAGE",
        "VECTOR_EMBEDDING_DIMENSIONS",
        "VECTOR_EMBEDDING_MAX_CHARS",
        "VECTOR_EMBEDDING_MODEL",
        "VECTOR_EMBEDDING_PROVIDER",
        "VECTOR_EMBEDDING_TIMEOUT_MS",
        "VECTOR_STORE",
        "WEB_SEARCH_PROVIDER",
        "WEEKLY_RECAP_ENABLED",
        "WHATSAPP_LOGIN_MODE",
        "WHATSAPP_LOGIN_TOKEN",
        "WHATSAPP_SAFETY_AUTO_PAUSE_AT",
        "WHATSAPP_SAFETY_DAY1_LIMIT",
        "WHATSAPP_SAFETY_ENABLED",
        "WHATSAPP_SAFETY_MAX_DELAY_MS",
        "WHATSAPP_SAFETY_MAX_PER_DAY",
        "WHATSAPP_SAFETY_MAX_PER_HOUR",
        "WHATSAPP_SAFETY_MAX_PER_MINUTE",
        "WHATSAPP_SAFETY_MIN_DELAY_MS",
        "WHATSAPP_SAFETY_WARMUP_DAYS",
      ]
    `);
    expect({
      platform: config.MESSAGING_PLATFORM,
      providerOrder: config.AI_PROVIDER_ORDER,
      owner: config.OWNER_JID,
      logLevel: config.LOG_LEVEL,
      bridge: {
        instanceId,
        configuredInstanceId: config.INSTANCE_ID,
        enabled: config.BRIDGE_ENABLED,
        transport: config.BRIDGE_TRANSPORT,
        brokerUrl: config.BRIDGE_BROKER_URL,
        summaryMinutes: config.BRIDGE_SUMMARY_INTERVAL_MINUTES,
        maxText: config.BRIDGE_MAX_TEXT,
        sharedMemory: config.SHARED_MEMORY_ENABLED,
        sharedCollection: config.QDRANT_SHARED_COLLECTION,
      },
      modelDefaults: {
        openAiReasoningEffort: config.OPENAI_REASONING_EFFORT,
        cloudMaxTokens: config.CLOUD_MAX_TOKENS,
      },
      tokens: {
        monitoring: config.MONITORING_TOKEN,
        qdrant: config.QDRANT_API_KEY,
        supportMessage: config.SUPPORT_MESSAGE,
      },
      booleans: {
        promptCaching: config.ANTHROPIC_PROMPT_CACHING,
        toolCalling: config.AI_TOOL_CALLING,
        whatsappSafety: config.WHATSAPP_SAFETY_ENABLED,
        eventReminders: config.EVENT_REMINDERS_ENABLED,
        metrics: config.METRICS_ENABLED,
        admin: config.ADMIN_PAGE_ENABLED,
        weeklyRecap: config.WEEKLY_RECAP_ENABLED,
        discordGateway: config.DISCORD_GATEWAY_ENABLED,
        slackDemo: config.SLACK_DEMO,
        turnstile: config.DEMO_TURNSTILE_ENABLED,
        postgresSsl: config.POSTGRES_SSL,
        sessionMemory: config.CONTEXT_SESSION_MEMORY_ENABLED,
        memoryAutoExtract: config.MEMORY_AUTO_EXTRACT,
        bandFeatures: config.BAND_FEATURES_ENABLED,
      },
      numbers: {
        healthPort: config.HEALTH_PORT,
        slackEventsPort: config.SLACK_EVENTS_PORT,
        discordInteractionsPort: config.DISCORD_INTERACTIONS_PORT,
        postgresPort: config.POSTGRES_PORT,
        vectorDimensions: config.VECTOR_EMBEDDING_DIMENSIONS,
        retryTimeout: config.RETRY_ATTEMPT_TIMEOUT_MS,
        rehearsalReminderLead: config.REHEARSAL_REMINDER_LEAD_MINUTES,
      },
      urls: {
        ollama: config.OLLAMA_BASE_URL,
        qdrant: config.QDRANT_URL,
        searxng: config.SEARXNG_BASE_URL,
      },
    }).toMatchInlineSnapshot(`
      {
        "booleans": {
          "admin": false,
          "bandFeatures": true,
          "discordGateway": false,
          "eventReminders": false,
          "memoryAutoExtract": true,
          "metrics": true,
          "postgresSsl": true,
          "promptCaching": false,
          "sessionMemory": false,
          "slackDemo": true,
          "toolCalling": true,
          "turnstile": true,
          "weeklyRecap": false,
          "whatsappSafety": false,
        },
        "bridge": {
          "brokerUrl": "amqp://bridge-broker",
          "configuredInstanceId": "discord-band",
          "enabled": true,
          "instanceId": "discord-band",
          "maxText": 800,
          "sharedCollection": "test_shared_memory",
          "sharedMemory": true,
          "summaryMinutes": 9,
          "transport": "amqp",
        },
        "logLevel": "debug",
        "modelDefaults": {
          "cloudMaxTokens": 1024,
          "openAiReasoningEffort": "low",
        },
        "numbers": {
          "discordInteractionsPort": 4200,
          "healthPort": 3999,
          "postgresPort": 6543,
          "rehearsalReminderLead": 60,
          "retryTimeout": 9000,
          "slackEventsPort": 4100,
          "vectorDimensions": 768,
        },
        "owner": "test_owner@s.whatsapp.net",
        "platform": "whatsapp",
        "providerOrder": "openrouter,anthropic,openai",
        "tokens": {
          "monitoring": "monitoring-token",
          "qdrant": "qdrant-key",
          "supportMessage": "support us",
        },
        "urls": {
          "ollama": "http://localhost:11434",
          "qdrant": "http://qdrant.local:6333",
          "searxng": "http://searxng.local",
        },
      }
    `);
    expect(exitSpy).not.toHaveBeenCalled();
  });
});
