apiVersion: v1
kind: Service
metadata:
  name: {{ include "garbanzo.fullname" . }}
  labels:
    {{- include "garbanzo.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: health
      port: {{ .Values.healthPort }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "garbanzo.selectorLabels" . | nindent 4 }}
